name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build And Install All
      run: |
        chmod +x ./configure
        ./configure --prefix=$(pwd)/.actions --enable-install-peco
        make && make install
        ./actions/bin/coas ./demo
        [[ $? -eq 1 ]] && { echo Success }
