name: Build-Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        path: 'PECoAutoStage'
    - uses: actions/checkout@v2
      with:
        repository: 'littlepush/PEUtils'
        path: 'PEUtils'
    - uses: actions/checkout@v2
      with: 
        repository: 'littlepush/PECoTask'
        path: 'PECoTask'
    - uses: actions/checkout@v2
      with:
        repository: 'littlepush/PECoNet'
        path: 'PECoNet'
    - name: Create Temp Root
      run: mkdir test_root
    - name: Build Utils
      run: |
        cd PEUtils
        chmod +x ./configure
        ./configure --prefix=../test_root
        make && make install
        cd -
    - name: Build CoTask
      run: |
        cd PECoTask
        chmod +x ./configure
        ./configure --prefix=../test_root
        make && make install
        cd -
    - name: Build CoNet
      run: |
        cd PECoNet
        chmod +x ./configure
        ./configure --prefix=../test_root
        make && make install
        cd -
    - name: Build CoAS
      run: |
        cd PECoAutoStage
        chmod +x ./configure
        ./configure --prefix=../test_root
        make && make install
        ../test_root/bin/coas ./demo
        [[ $? -eq 1 ]] && { echo Success }
        cd -
